export enum TaskType {
  LAUNCH_BROWSER = "LAUNCH_BROWSER",
  PAGE_TO_HTML = "PAGE_TO_HTML",
  EXTRACT_TEXT_FROM_ELEMENT = "EXTRACT_TEXT_FROM_ELEMENT",
  FILL_INPUT = "FILL_INPUT",
  CLICK_ELEMENT = "CLICK_ELEMENT",
  WAIT_FOR_ELEMENT = "WAIT_FOR_ELEMENT",
  DELIVER_VIA_WEBHOOK = "DELIVER_VIA_WEBHOOK",
  EXTRACT_DATA_WITH_AI = "EXTRACT_DATA_WITH_AI",
  READ_PROPERTY_FROM_JSON = "READ_PROPERTY_FROM_JSON",
  ADD_PROPERTY_TO_JSON = "ADD_PROPERTY_TO_JSON",
  NAVIGATE_URL = "NAVIGATE_URL",
  SCROLL_TO_ELEMENT = "SCROLL_TO_ELEMENT",
  EXTRACT_HTML_FROM_ELEMENT = "EXTRACT_HTML_FROM_ELEMENT",
  TEXT_INPUT = "TEXT_INPUT",
  ELEMENT_ITERATOR = "ELEMENT_ITERATOR",
<<<<<<< HEAD
  GO_BACK = "GO_BACK",
=======
>>>>>>> 87ef017b4991c6448f5ea436abde663b69b51adb
}

export enum TaskParamType {
  STRING = "STRING",
  BROWSER_INSTANCE = "BROWSER_INSTANCE",
  SELECT = "SELECT",
  CREDENTIAL = "CREDENTIAL",
  TEXT_INPUT = "TEXT_INPUT",
  ELEMENT_ITERATOR = "ELEMENT_ITERATOR",
  NUMBER = "NUMBER",
  BOOLEAN = "BOOLEAN",
}

export interface TaskParam {
  name: string;
  type: TaskParamType;
  helperText?: string;
  required?: boolean;
  hideHandle?: boolean;
  useTextarea?: boolean;
  [key: string]: any;
}
